version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${API_SERVER_PORT}:8000
    command: bash -c "alembic upgrade head && uvicorn app:create_app --host 0.0.0.0 --port 8000"


  postgres:
    container_name: postgres
    image: "postgres:13.1"
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 5


networks:
  default:
    name: shared-network
